const $menu = document.getElementById('menu')
const $activeMenu = document.getElementById('activeMenu')
const $hamburger = document.getElementById('hamburger')
const $phoneImage = document.getElementById('phoneImage')
const $landingImg = document.getElementById('landing__img')
const $landingText = document.getElementById('landing__text')
const $iconClose = document.getElementById('close')
const $icons = document.getElementById('icons')
const $body = document.getElementById('body')

$icons.addEventListener('click', () => {
    $menu.classList.toggle('active__container')
    $menu.classList.toggle('menu')
    $activeMenu.classList.toggle('activeMenu')
    $activeMenu.classList.toggle('nav__menu')
    $phoneImage.classList.toggle('phone__image')
    $landingImg.classList.toggle('background__main')
    $landingImg.classList.toggle('landing__img')
    $landingText.classList.toggle('landing__text')
    $landingText.classList.toggle('text')
    $iconClose.classList.toggle('close')
    $hamburger.classList.toggle('close')
    $body.classList.toggle('overflow')
})